# render.yaml

services:
  - name: Craftey-0.0.1-SNAPSHOT
    type: web
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/Craftey-0.0.1-SNAPSHOT.jar
    env:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: your-database-name
          property: username
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: your-database-name
          property: password
    healthCheckPath: "/actuator/health"